version: "3.2"

services:
  database:
    image: postgres
    container_name: dbdeliveryboy
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=admin 
      - POSTGRES_DB=  
    volumes:
      - pgdata:/data/postgres
    networks: 
      - bridge

  # app:
  #   build: 
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: deliveryboy
  #   ports:
  #     - 3333:3333
  #     - 9229:9229 #Você pode inserir essa porta tbm pra poder usar o debug
  #   volumes:
  #     - .:/usr/app
  #   networks: 
  #     - bridge
  #   depends_on:
  #     - database

networks:
  bridge:
volumes:
  pgdata: